# -*- coding: utf-8 -*-
"""HydratingTweets.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zqMOWOiWx5FFYiW-EmH21TXSRf2pQM1Y
"""

from twarc import Twarc

consumer_key = "zV9NpesB6qdytvyi3GDpREEhk"
consumer_secret = "uzECwlEqfz4Pj7fawkIvLwE81zrGOyhWpJ4cUJTQ6DF2MufVWs"
access_key = "1592302414182260736-0vavMgY6qmXEkHBkP9i8obLpG399nN"
access_secret = "6rypViyoG3G699ZslLvQApfVwEecwA4UxYAD9GNTkzy9E"

t = Twarc(consumer_key, consumer_secret, access_key, access_secret)

from zipfile import ZipFile
import os
import pandas as pd

import csv

count = 0

filenames = input("Enter filenames:")
filenames = filenames.split(":")
special = True

if special:
  for folder in filenames:
    for file in os.listdir(folder):
      print(f"Reading filename {file}")
      if file.endswith(".zip"):
        with ZipFile(os.path.join(folder, file)) as zf:
          for zip_file in zf.namelist():
            print(f"Processing {zip_file}")
            temp_name = os.path.join("temp", f"{os.path.basename(zip_file)[:-4]}.csv")

            if "__MACOSX" not in zip_file and zip_file.endswith(".csv"):
              print(f"At {temp_name}")
              count += 1
              if not os.path.exists(temp_name):
                with zf.open(zip_file) as z:
                  data = pd.read_csv(z, encoding="utf-8",sep=",", names=['id', 'score'])
                  data = data['id'].sample(n=13800, random_state=1)              
                  data.to_csv(temp_name,index=False, header=False)  

                name = os.path.join("hydrated",f"{os.path.basename(folder)[:-4]}_{count//20}_sampled.csv")
                print(f"Writing to {name}")
                with open(name, 'a+', encoding="utf-8", newline="") as f:  
                  for tweet in t.hydrate(open(temp_name)):
                    fields = [tweet['created_at'], tweet['full_text'], tweet['user']['followers_count'], tweet['user']['location'], tweet['retweet_count'], tweet['favorite_count'], tweet['entities']['hashtags']]
                    writer = csv.writer(f)
                    writer.writerow(fields)

                print("Done hydrating!")
            else:
              print(f"{zip_file} already done...")

else:
  for filename in filenames:
    count = 0
    print(f"Reading filename {filename}")
    if filename.endswith(".zip"):
      with ZipFile(filename) as zf:
        for zip_file in zf.namelist():
          print(f"Processing {zip_file}")
          temp_name = os.path.join("temp", f"{os.path.basename(zip_file)[:-4]}.csv")
          if "__MACOSX" not in zip_file and zip_file.endswith(".zip"):
            print(f"At {temp_name}")
            count += 1
            if not os.path.exists(temp_name):
              with zf.open(zip_file) as z:
                try:
                  data = pd.read_csv(z, compression="zip",sep=",", names=['id', 'score'])
                  data = data['id'].sample(n=13800, random_state=1)              
                  data.to_csv(temp_name,index=False, header=False)  
                except ValueError: 
                  print(f"{zip_file} has multiple, aiyo...")

              name = os.path.join("hydrated",f"{os.path.basename(filename)[:-4]}_{count//20}_sampled.csv")
              print(f"Writing to {name}")
              with open(name, 'a+', encoding="utf-8", newline="") as f:  
                for tweet in t.hydrate(open(temp_name)):
                  fields = [tweet['created_at'], tweet['full_text'], tweet['user']['followers_count'], tweet['user']['location'], tweet['retweet_count'], tweet['favorite_count'], tweet['entities']['hashtags']]
                  writer = csv.writer(f)
                  writer.writerow(fields)

              print("Done hydrating!")
            else:
              print(f"{zip_file} already done...")


